name: Build and Release
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, build-prod
      run: |
        npm install
        npm run build
        npm run build-prod
    - name: Release Github Pages
      uses: igolopolosov/github-action-release-github-pages@master
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        GITHUB_PAGES_REPO_AUTHOR: igolopolosov
        GITHUB_PAGES_REPO_NAME: igolopolosov.github.io
        GITHUB_PAGES_RELEASE_BRANCH: master
        PROJECT_BUILD_FOLDER: /
        GITHUB_PAGES_CLEANUP_SCRIPT: "rm bundle* && rm index.html"
